### ISSUE TITLE
The animation is very good👍,Whether to support screen edge hiding and PinchGesture in Upcoming Features? 

### ISSUE THREAD

**Issue by qiuyuliang** [duraidabdul/LocalConsole#1]
Automatically hides when you move to the edge of the screen like PiP-style

**Comment by duraidabdul** [comment]
Thanks for the feedback! I will try to add screen hiding in a future release!

As for pinch to resize, that is a pretty difficult feature to implement because I'd want to build a proper rotation and touch tracking resize gesture (similar to the way the native video PiP zooms), not a simple scale in the way UIPinchGestureRecognizer works. For the time being, I'm planning to add an option to choose the console size programmatically, kind of like this:

`localConsoleManager.consoleSize = CGSize(width: 300, height: 200)`

I've already started implementing the programmatic console sizing method, so you can expect this option in the next release!

**Comment by qiuyuliang** [comment]
Thank you for your reply
